Create aarch64 build of qemu (x86_64) right now.

diff --git a/qemu-aarch64/Dockerfile b/qemu-aarch64/Dockerfile
--- a/qemu-aarch64/Dockerfile
+++ b/qemu-aarch64/Dockerfile
@@ -8,20 +8,32 @@ RUN apt update && \
         build-essential ca-certificates git make \
         python3 wget pkg-config  	libglib2.0-0 libglib2.0-dev libpixman-1-dev \
         libmount-dev libffi-dev libselinux1-dev libcap-ng-dev libattr1-dev \
-        crossbuild-essential-arm64 gcc-10-aarch64-linux-gnu nettle-dev
+        crossbuild-essential-arm64 gcc-10-aarch64-linux-gnu nettle-dev ninja-build
 
-RUN wget - O "qemu-5.1.0.tar.xz" https://download.qemu.org/qemu-5.1.0.tar.xz && \
-  echo c9174eb5933d9eb5e61f541cd6d1184cd3118dfe4c5c4955bc1bdc4d390fa4e5 "qemu-5.1.0.tar.xz" | \
-  shas256sum -C || (echo "qemu-5.1.0.tar.xz checksum verification failed!" && exit 1) && \
-  tar xvJf qemu-5.1.0.tar.xz -C qemu
+RUN apt update && \
+    DEBIAN_FRONTEND=noninteractive \
+    apt install -y --no-install-recommends \
+        libcap-ng-dev:arm64 \
+        libpixman-1-dev:arm64 \
+        libglib2.0-dev:arm64 \
+        libbz2-dev:arm64 \
+        liblzo2-dev:arm64 \
+        librdmacm-dev:arm64 \
+        libsnappy-dev:arm64 \
+        libxen-dev:arm64
+
+RUN wget -q -O "qemu-6.0.0.tar.xz" https://download.qemu.org/qemu-6.0.0.tar.xz && \
+  echo "87bc1a471ca24b97e7005711066007d443423d19aacda3d442558ae032fa30b9  qemu-6.0.0.tar.xz" | \
+  sha256sum --check --status || (echo "qemu-6.0.0.tar.xz checksum verification failed!" && exit 1) && \
+  tar -xf qemu-6.0.0.tar.xz
 
 # --without-default-devices
+ # --static \
 RUN mkdir build && \
   cd build && \
-  /qemu/configure \
+  ../qemu-6.0.0/configure \
   --cross-prefix=aarch64-linux-gnu- \
   --target-list=x86_64-softmmu \
-  --static \
   --audio-drv-list="" \
   --enable-virtfs \
   --enable-vhost-vsock \
@@ -49,22 +61,17 @@ RUN mkdir build && \
   --disable-live-block-migration \
   --without-default-devices
 
-RUN echo CONFIG_PARALLEL=y >> build/config-host.mak
-RUN echo CONFIG_VIRTIO=y >> build/config-host.mak
-RUN echo CONFIG_VIRTIO_SERIAL=y >> build/config-host.mak
-RUN echo CONFIG_VIRTIO_PCI=y >> build/config-host.mak
-RUN echo CONFIG_VIRTIO_RNG=y >> build/config-host.mak
-RUN echo CONFIG_VIRTIO_MMIO=y >> build/config-host.mak
-RUN echo CONFIG_VIRTIO_SCSI=y >> build/config-host.mak
-RUN echo CONFIG_VIRTIO_BLK=y >> build/config-host.mak
-RUN echo CONFIG_VIRTIO_9P=y >> build/config-host.mak
-RUN echo CONFIG_FSDEV_9P=y >> build/config-host.mak
+RUN echo CONFIG_PARALLEL=y >> config-host.mak && \
+echo CONFIG_VIRTIO=y >> config-host.mak && \
+echo CONFIG_VIRTIO_SERIAL=y >> config-host.mak && \
+echo CONFIG_VIRTIO_PCI=y >> config-host.mak && \
+echo CONFIG_VIRTIO_RNG=y >> config-host.mak && \
+echo CONFIG_VIRTIO_MMIO=y >> config-host.mak && \
+echo CONFIG_VIRTIO_SCSI=y >> config-host.mak && \
+echo CONFIG_VIRTIO_BLK=y >> config-host.mak && \
+echo CONFIG_VIRTIO_9P=y >> config-host.mak && \
+echo CONFIG_FSDEV_9P=y >> config-host.mak
 
-
-RUN cd build && make x86_64-softmmu/all V=1 CFLAGS+="-Os -flto" -j4 LIBS+="-flto -lblkid -luuid -lpixman-1 -lutil"
-#RUN cd build && make x86_64-softmmu/all V=1 LIBS+="-flto -lblkid -luuid -lpixman-1 -lutil" CONFIG_PARALLEL=y CONFIG_VIRTIO_SERIAL=y
-
-#RUN cd build/x86_64-softmmu && -lmount -lblkid -luuid
-
+RUN cd build && make -j$(nproc)
 RUN cp /build/x86_64-softmmu/qemu-system-x86_64 vmrt-aarch64
 
